name: Action CI

on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run my own container action
        uses: ./
        with:
          myInput: '@wulfland'